# Generated by Django 4.2.1 on 2023-05-10 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='description_en',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='products',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='products',
            name='gender_en',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('for kids', 'for kids')], max_length=100, null=True, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='products',
            name='gender_ru',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('for kids', 'for kids')], max_length=100, null=True, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='products',
            name='title_en',
            field=models.CharField(max_length=50, null=True, verbose_name='Name product'),
        ),
        migrations.AddField(
            model_name='products',
            name='title_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='Name product'),
        ),
    ]
