# Generated by Django 4.2.1 on 2023-05-10 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0002_products_description_en_products_description_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='gender_en',
        ),
        migrations.RemoveField(
            model_name='products',
            name='gender_ru',
        ),
    ]
