# Generated by Django 4.2.1 on 2023-05-11 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0003_remove_products_gender_en_remove_products_gender_ru'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='products',
            name='title_ru',
        ),
    ]
